var classes = [
    {
        "name": "AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dashboard",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "manageUsers",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "manageOrders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "manageCourses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "viewLogs",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotalCourses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllCourses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logActivity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 8,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 23,
        "ccn": 14,
        "ccnMethodMax": 6,
        "externals": [
            "Database",
            "User",
            "Order",
            "Database",
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 181,
        "vocabulary": 60,
        "volume": 1069.15,
        "difficulty": 9.77,
        "effort": 10444.75,
        "level": 0.1,
        "bugs": 0.36,
        "time": 580,
        "intelligentContent": 109.44,
        "number_operators": 54,
        "number_operands": 127,
        "number_operators_unique": 8,
        "number_operands_unique": 52,
        "cloc": 0,
        "loc": 110,
        "lloc": 110,
        "mi": 32.38,
        "mIwoC": 32.38,
        "commentWeight": 0,
        "kanDefect": 0.79,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 324.11,
        "totalStructuralComplexity": 3240,
        "totalDataComplexity": 1.11,
        "totalSystemComplexity": 3241.11,
        "package": "\\",
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyRegistration",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendVerificationCode",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logActivity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 25,
        "ccn": 19,
        "ccnMethodMax": 9,
        "externals": [
            "Database",
            "User"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 298,
        "vocabulary": 73,
        "volume": 1844.57,
        "difficulty": 16.67,
        "effort": 30742.8,
        "level": 0.06,
        "bugs": 0.61,
        "time": 1708,
        "intelligentContent": 110.67,
        "number_operators": 88,
        "number_operands": 210,
        "number_operators_unique": 10,
        "number_operands_unique": 63,
        "cloc": 8,
        "loc": 133,
        "lloc": 125,
        "mi": 47.38,
        "mIwoC": 28.83,
        "commentWeight": 18.54,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.05,
        "relativeSystemComplexity": 49.05,
        "totalStructuralComplexity": 343,
        "totalDataComplexity": 0.38,
        "totalSystemComplexity": 343.38,
        "package": "\\",
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CartController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCartItems",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateTotal",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 10,
        "ccnMethodMax": 4,
        "externals": [
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 119,
        "vocabulary": 36,
        "volume": 615.22,
        "difficulty": 11.43,
        "effort": 7031.1,
        "level": 0.09,
        "bugs": 0.21,
        "time": 391,
        "intelligentContent": 53.83,
        "number_operators": 39,
        "number_operands": 80,
        "number_operators_unique": 8,
        "number_operands_unique": 28,
        "cloc": 0,
        "loc": 65,
        "lloc": 65,
        "mi": 39.58,
        "mIwoC": 39.58,
        "commentWeight": 0,
        "kanDefect": 0.87,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 36.45,
        "totalStructuralComplexity": 216,
        "totalDataComplexity": 2.71,
        "totalSystemComplexity": 218.71,
        "package": "\\",
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CourseController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "home",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logActivity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 22,
        "ccn": 15,
        "ccnMethodMax": 6,
        "externals": [
            "Database",
            "Course"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 179,
        "vocabulary": 43,
        "volume": 971.3,
        "difficulty": 9.97,
        "effort": 9686.76,
        "level": 0.1,
        "bugs": 0.32,
        "time": 538,
        "intelligentContent": 97.39,
        "number_operators": 56,
        "number_operands": 123,
        "number_operators_unique": 6,
        "number_operands_unique": 37,
        "cloc": 0,
        "loc": 87,
        "lloc": 87,
        "mi": 34.76,
        "mIwoC": 34.76,
        "commentWeight": 0,
        "kanDefect": 0.71,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.06,
        "relativeSystemComplexity": 49.06,
        "totalStructuralComplexity": 392,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 392.5,
        "package": "\\",
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "success",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCartItems",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateTotal",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveOrderItems",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendOrderEmail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logActivity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 11,
        "ccnMethodMax": 6,
        "externals": [
            "Database",
            "Order",
            "Database",
            "Database",
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 218,
        "vocabulary": 66,
        "volume": 1317.68,
        "difficulty": 10.41,
        "effort": 13722.03,
        "level": 0.1,
        "bugs": 0.44,
        "time": 762,
        "intelligentContent": 126.53,
        "number_operators": 67,
        "number_operands": 151,
        "number_operators_unique": 8,
        "number_operands_unique": 58,
        "cloc": 0,
        "loc": 100,
        "lloc": 100,
        "mi": 33.05,
        "mIwoC": 33.05,
        "commentWeight": 0,
        "kanDefect": 1.03,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 144.28,
        "totalStructuralComplexity": 1152,
        "totalDataComplexity": 2.23,
        "totalSystemComplexity": 1154.23,
        "package": "\\",
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrderItems",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "changePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logActivity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 21,
        "ccnMethodMax": 11,
        "externals": [
            "Database",
            "User",
            "Order",
            "Database",
            "Database",
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 320,
        "vocabulary": 78,
        "volume": 2011.33,
        "difficulty": 16.32,
        "effort": 32831.98,
        "level": 0.06,
        "bugs": 0.67,
        "time": 1824,
        "intelligentContent": 123.22,
        "number_operators": 98,
        "number_operands": 222,
        "number_operators_unique": 10,
        "number_operands_unique": 68,
        "cloc": 7,
        "loc": 146,
        "lloc": 139,
        "mi": 43.93,
        "mIwoC": 27.3,
        "commentWeight": 16.64,
        "kanDefect": 1.61,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.12,
        "relativeSystemComplexity": 100.12,
        "totalStructuralComplexity": 600,
        "totalDataComplexity": 0.73,
        "totalSystemComplexity": 600.73,
        "package": "\\",
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]